name: Phoneix Test Automation Automation Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Execute Test Automation framework
        run: |
          echo "Current directory:"
          pwd
          echo "Listing files in current directory:"
          ls -R
          cd PhoniexTestAutomationFramework
          echo "Now inside PhoniexTestAutomationFramework folder"
          ls -l
          mvn clean test -DsuiteXmlFile=testng.xml -Denv=qa

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            PhoniexTestAutomationFramework/target/surefire-reports/
            PhoniexTestAutomationFramework/target/allure-results/
          retention-days: 7
